# Ejemplo 2 · Resolución (docente)

In [ ]:
import pandas as pd
ventas = pd.DataFrame({
    "categoria": ["Electrónica"]*4 + ["Ropa"]*4,
    "producto": ["Celular","Tablet","Auriculares","Cargador","Campera","Jeans","Remera","Medias"],
    "ventas": [900,700,700,200,500,400,400,100]})
ventas

     categoria     producto  ventas
0  Electrónica      Celular     900
1  Electrónica       Tablet     700
2  Electrónica  Auriculares     700
3  Electrónica     Cargador     200
4         Ropa      Campera     500
5         Ropa        Jeans     400
6         Ropa       Remera     400
7         Ropa       Medias     100

## a) Ranking
- `rn`: `cumcount` tras ordenar (desempata por orden de aparición)
- `rnk`: `method='min'` → salta posiciones tras un empate
- `drnk`: `method='dense'` → no salta

In [ ]:
g = ventas.groupby('categoria')['ventas']
ventas['rn'] = (ventas.sort_values('ventas', ascending=False, kind='stable')
                .groupby('categoria').cumcount() + 1)
ventas['rnk'] = g.rank(method='min', ascending=False).astype(int)
ventas['drnk'] = g.rank(method='dense', ascending=False).astype(int)
ventas

     categoria     producto  ventas  rn  rnk  drnk
0  Electrónica      Celular     900   1    1     1
1  Electrónica       Tablet     700   2    2     2
2  Electrónica  Auriculares     700   3    2     2
3  Electrónica     Cargador     200   4    4     3
4         Ropa      Campera     500   1    1     1
5         Ropa        Jeans     400   2    2     2
6         Ropa       Remera     400   3    2     2
7         Ropa       Medias     100   4    4     3

## b) Porcentaje de la categoría

In [ ]:
ventas['pct'] = (100 * ventas['ventas'] / g.transform('sum')).round(1)
ventas

     categoria     producto  ventas  rn  rnk  drnk   pct
0  Electrónica      Celular     900   1    1     1  36.0
1  Electrónica       Tablet     700   2    2     2  28.0
2  Electrónica  Auriculares     700   3    2     2  28.0
3  Electrónica     Cargador     200   4    4     3   8.0
4         Ropa      Campera     500   1    1     1  35.7
5         Ropa        Jeans     400   2    2     2  28.6
6         Ropa       Remera     400   3    2     2  28.6
7         Ropa       Medias     100   4    4     3   7.1

## c) Top 2 por categoría
Salen 3 filas por categoría porque el empate en el puesto 2 obliga a incluir ambos productos.

In [ ]:
top2 = (ventas[ventas['drnk'] <= 2]
        .sort_values(['categoria','drnk'])[['categoria','producto','ventas','drnk']])
top2

     categoria     producto  ventas  drnk
0  Electrónica      Celular     900     1
1  Electrónica       Tablet     700     2
2  Electrónica  Auriculares     700     2
4         Ropa      Campera     500     1
5         Ropa        Jeans     400     2
6         Ropa       Remera     400     2